version: '3.4'

services:
  db_dev:
    container_name: database
    image: postgres:11.3
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "0.0.0.0:5432:5432"
    expose:
      - "5432"
    networks:
      - my-network

  my_app:
    container_name: Api
    build: .
    ports:
      - "0.0.0.0:5550:5000"
      - "0.0.0.0:5555:5001"
    expose:
      - "5555"
      - "5550"
    depends_on:
      - db_dev
    environment: 
      DB_TEST_SERVER: database
      DB_TEST_PORT: 5432
      DB_TEST_DATABASE: test
      DB_TEST_USER: test
      DB_TEST_PASSWORD: test
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - my-network

networks:
  my-network:
    external: true
